import os


APP_VERSION = os.getenv('APP_VERSION')
SCRET_KEY = os.getenv('SCRET_KEY', '1YRmJ0MI8nX5uCJZPqf2B6Md8F_yC9eW0w2CZgNAbU8')
ALGORITHM = os.getenv('ALGORITHM')
REFRESH_TOKEN_EXPIRES = os.getenv('REFRESH_TOKEN_EXPIRES', 43200)
ACCESS_TOKEN_EXPIRES = os.getenv('ACCESS_TOKEN_EXPIRES', 1)
PREFIX = f"/{APP_VERSION}/api"
MEMCACHED_ENDPOINT = os.getenv('MEMCACHED_ENDPOINT', 'memcached')
MEMCACHED_PORT = os.getenv('MEMCACHED_PORT', 11211)